# Generated by Django 3.1.3 on 2020-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=40, unique=True)),
                ('redeemed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('pwd', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('voters', models.IntegerField()),
            ],
        ),
    ]
